cmake_minimum_required(VERSION 2.8)

# Include Directories

set(TZ10XX_DFP_DRIVER_INCLUDE_DIRECTORIES
  "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver"
)

include_directories(
  ${TZ10XX_DFP_DRIVER_INCLUDE_DIRECTORIES}
)

# Sources

set(TZ10XX_DFP_DRIVER_SOURCES
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/ACCEL_GYRO_TZ10xx.c"
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/ACCEL_TZ10xx.c"
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/ADCC12_TZ10xx.c"
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/ADCC24_TZ10xx.c"
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/ADVTMR_TZ10xx.c"
  "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/GPIO_TZ10xx.c"
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/GYRO_TZ10xx.c"
  "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/I2C_TZ10xx.c"
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/MAG_TZ10xx.c"
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/NOR_TZ10xx.c"
  "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/PMU_TZ10xx.c"
  "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/RNG_TZ10xx.c"
  "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/RTC_TZ10xx.c"
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/SDMAC_TZ10xx.c"
  "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/SPI_TZ10xx.c"
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/SRAMC_TZ10xx.c"
  "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/TMR_TZ10xx.c"
  "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/UART_TZ10xx.c"
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/USBD_TZ10xx.c"
# "$ENV{SDK_DIR}TOSHIBA.TZ10xx_DFP/RTE_Driver/WDT_TZ10xx.c"
)

add_library(tz10xx_dfp_dirver ${TZ10XX_DFP_DRIVER_SOURCES})